import type { Module } from "./catalog";

export const ozModules: Module[] = [
  {
    id: "oz-erc20",
    name: "ERC-20",
    description: "Standard fungible token",
    category: "oz",
    tags: ["token", "fungible", "defi"],
    importPath: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
    docsUrl: "https://docs.openzeppelin.com/contracts/5.x/erc20",
  },
  {
    id: "oz-erc721",
    name: "ERC-721",
    description: "Non-fungible token (NFT)",
    category: "oz",
    tags: ["token", "nft", "collectible"],
    importPath: "@openzeppelin/contracts/token/ERC721/ERC721.sol",
    docsUrl: "https://docs.openzeppelin.com/contracts/5.x/erc721",
  },
  {
    id: "oz-erc1155",
    name: "ERC-1155",
    description: "Multi-token standard",
    category: "oz",
    tags: ["token", "multi", "gaming"],
    importPath: "@openzeppelin/contracts/token/ERC1155/ERC1155.sol",
    docsUrl: "https://docs.openzeppelin.com/contracts/5.x/erc1155",
  },
  {
    id: "oz-ownable",
    name: "Ownable",
    description: "Single-owner access control",
    category: "oz",
    tags: ["access", "ownership"],
    importPath: "@openzeppelin/contracts/access/Ownable.sol",
  },
  {
    id: "oz-access-control",
    name: "AccessControl",
    description: "Role-based access control",
    category: "oz",
    tags: ["access", "roles"],
    importPath: "@openzeppelin/contracts/access/AccessControl.sol",
  },
  {
    id: "oz-pausable",
    name: "Pausable",
    description: "Emergency stop mechanism",
    category: "oz",
    tags: ["security", "pause"],
    importPath: "@openzeppelin/contracts/utils/Pausable.sol",
  },
  {
    id: "oz-reentrancy-guard",
    name: "ReentrancyGuard",
    description: "Reentrancy attack protection",
    category: "oz",
    tags: ["security", "reentrancy"],
    importPath: "@openzeppelin/contracts/utils/ReentrancyGuard.sol",
  },
  {
    id: "oz-erc20-votes",
    name: "ERC20Votes",
    description: "Token with voting power",
    category: "oz",
    tags: ["governance", "voting", "token"],
    importPath: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol",
  },
  {
    id: "oz-governor",
    name: "Governor",
    description: "On-chain governance system",
    category: "oz",
    tags: ["governance", "dao"],
    importPath: "@openzeppelin/contracts/governance/Governor.sol",
  },
  {
    id: "oz-upgradeable",
    name: "UUPSUpgradeable",
    description: "UUPS proxy pattern",
    category: "oz",
    tags: ["proxy", "upgrade"],
    importPath: "@openzeppelin/contracts/proxy/utils/UUPSUpgradeable.sol",
  },
];
